### ISSUE TITLE
Issues with documentation and examples

### ISSUE THREAD

**Issue by omarabid** [milliams/plotlib#14]
Documentation is lacking and various examples are not working. What plans do you have for the docs/examples? Are you working on this fulltime?

**Comment by milliams** [comment]
I am not working on this full-time, it's a side project as a hobby.

I haven't yet taken the time to fully flesh out the documentation as the high-level API is still subject to change. However, any examples will be valid for the code they are next to. If you want documentation for a released version of plotlib then I suggest using [docs.rs](https://docs.rs/plotlib) or browsing the source at a particular [git tag](https://github.com/milliams/plotlib/tree/0.3.0).
