### ISSUE TITLE
Error handling (when saving, but also generally)

### ISSUE THREAD

**Issue by Ploppz** [milliams/plotlib#17]
`Page::save` silently does nothing when the file extension is not one of a supported format. It should return an error, in my opinion. The reason I make an issue instead of fixing it myself is: what error should it return?

I think we should use the `failure` crate. But then the question is: should we make an enum for possible errors, or just `bail!("some text message")`? Not sure what is common to do.

**Comment by mindriot101** [comment]
Hi, what version of the code are you using? For the current master (61ebe6e0b7f45dd9c6ea9a809cad6b93b4072540), in the "scatter_svg" example, the "save" method returns a `Result<(), failure::Error>`:

https://github.com/milliams/plotlib/blob/61ebe6e0b7f45dd9c6ea9a809cad6b93b4072540/examples/scatter_svg.rs#L29-L31

@milliams: it looks like we should do another release fairly soon.

**Comment by Ploppz** [comment]
You are right! I don't know why I thought it doesn't use `failure`, and I don't see any problem anymore...

**Comment by mindriot101** [comment]
@Ploppz version [0.4.0](https://crates.io/crates/plotlib/0.4.0) is now on [crates.io](https://crates.io) so this error handling should be available in the released version.
