### ISSUE TITLE
Enum for named colors?

### ISSUE THREAD

**Issue by Ploppz** [milliams/plotlib#19]
Just an idea: to have an enum with the named colors for SVG, like "burlywood". However, this would maybe not work for other formats... but neither would the string "burlywood". The enum could have a variant `Hex(u32)` or `Hex(String)`.
So I am not sure; opening this for discussion.

**Comment by mindriot101** [comment]
See named colours [here](https://www.december.com/html/spec/colorsvg.html)

There could be scope for e.g. `ToHex` trait for the named colours. It could also be generated at build time via `build.rs`.

**Comment by Ploppz** [comment]
hmm on second thought maybe that page is enough because when selecting a color, you probably want to see what it looks like anyway (which you can on that page). Feel free to close.
