### ISSUE TITLE
Difficulty getting started with examples

### ISSUE THREAD

**Issue by quietlychris** [milliams/plotlib#22]
I'm interested in doing some data exploration in Rust, and plotlib looks like it is a promising tool for helping to visualize some things, without having to go through the trouble of writing the data to file and plotting with Python or such. 

Unfortunately, I'm having getting trouble starting up with plotlib at the moment. I'd primarily like to focus on an issue I'm having with the first function in the tests file, `test_no_data.rs`, called `test_data_with_one_length()`. This seems like sort of the basic "Hello, world!" of the running a scatter graph, although the current example listed on home page `README` also doesn't compile at the moment. For reference, I'm using Rust 1.32.0-stable, on Ubuntu 18.04 LTS. My `cargo.toml` file has the most recent crate available,  `plotlib = "0.3"`.

The function `test_data_with_one_length()` has the following code, which I'm using in  `main()`:
```
    // Scatter plots expect a list of pairs
    let data1 = [(-3.0, 2.3)];

    // We create our scatter plot from the data
    let s1 = Scatter::from_slice(&data1).style(
        scatter::Style::new()
            .marker(Marker::Square) // setting the marker to be a square
            .colour("#DD3355"),
    ); // and a custom colour

    // The 'view' describes what set of data is drawn
    let v = ContinuousView::new()
        .add(&s1)
        .x_range(-5., 10.)
        .y_range(-2., 6.)
        .x_label("Some varying variable")
        .y_label("The response of something");

    // A page with a single view is then saved to an SVG file
    Page::single(&v)
        .save("/tmp/scatter_one_length.svg")
.unwrap();
``` 
This produces three main errors:

1. `ContinuousView` is not an available function. I've confirmed this with the `crates.io` documentation, and when `let v = ContinuousView::new()` is replaced with `View::new()`, the error goes away.
2.  `Scatter::from_slice(&data1)` is not valid, as the `::as_slice()` method doesn't appear in the documentation at all. However, when this is replaced with `::from_vec()` instead, this error disappears as well.
3. `unwrap()` doesn't appear to be implemented for `Page::save()`, but we can put a quick hold on error handling and remove that for the time being.

At this point, `cargo build` finishes successfully. However, when I try actually running this example, the program panics with the following message:
`thread 'main' panicked at 'assertion failed: lower < upper', /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/plotlib-0.3.0/src/axis.rs:15:9`

I don't have an obvious solution for fixing this (since the numbers in the axis ranges seem valid) according to the `axis.rs` bounds checker, so wanted to bring it to your attention. I'm looking forward to have a native library like this be available (as I'm sure others are), and appreciate the time you've put into it so far. Thanks, and if you have any questions on reproducing these bugs, please let me know.

**Comment by mindriot101** [comment]
Hi @quietlychris, thanks for submitting this feedback. What you've uncovered here is that the crate has not been updated in a while on crates.io. The tests you refer to, along with the README have advanced beyond the latest release.

You're also not the first to notice this (https://github.com/milliams/plotlib/issues/17) so our advice for the time being is to follow the `master` git branch and build any documentation yourself, if needed. This way the tests and examples on github will be valid for the code that you are using.

Sorry for the confusion. We are encouraged to hear your excitement for the project!

## Cargo.toml

```toml
[dependencies]
plotlib = { git = "https://github.com/milliams/plotlib", branch = "master" }
```

## Documentation

```sh
cargo doc --open
```

**Comment by quietlychris** [comment]
Thanks for getting back to me, @mindriot101! That makes sense, and I've confirmed that using the master git branch in my `Cargo.toml` file lets everything compile and run without issues.

Just out of curiosity, are there any plans to push some of the progress here on GH to an update on crates.io in the near future? Or is there a particular milestone that the dev team is looking to hit before moving in that direction?

**Comment by milliams** [comment]
We're planning on a 0.4.0 release in the very near future. We'll just wait for https://github.com/milliams/plotlib/milestone/2 to be ready and we'll put it out.

**Comment by mindriot101** [comment]
@quietlychris version [0.4.0](https://crates.io/crates/plotlib/0.4.0) is now out so the tests and examples should match the crate available from [crates.io](https://crates.io) now.

**Comment by quietlychris** [comment]
@mindriot101 Awesome, thanks!
