### ISSUE TITLE
Wrong example for scatterplot

### ISSUE THREAD

**Issue by AntonOellerer** [milliams/plotlib#52]
Hey
I tried to implement a scattterplot similar to the example and noticed that I need to use `use plotlib::scatter::Scatter;` instead of `use plotlib::repr::Scatter;` as written in the example project.

**Comment by AntonOellerer** [comment]
Here is a pull request fixing it : https://github.com/milliams/plotlib/pull/53

**Comment by AntonOellerer** [comment]
The pull request also fixes this problem in the examples

**Comment by milliams** [comment]
Thanks for the report but this is due to the README and examples being correct for the master branch which has changed since the last 0.4 release. The correct fix for this is for me to make another release which I will do as soon as I can.
