### ISSUE TITLE
Fix examples

### ISSUE THREAD

**Issue by tolvanea** [milliams/plotlib#54]
None of the examples compile, probably due to the refactoring of modules hierarchy.

Also, it would be nice, if output images of examples are uploaded, because then it would be easier to glance the capabilities of this library.

**Comment by milliams** [comment]
All of the examples seem to be building for me (including in the CI). Most likely you are looking at the examples in the master branch here on GitHub while using the 0.4.0 release. You can see the examples for 0.4.0 at https://github.com/milliams/plotlib/tree/0.4.0/examples but I will also soon be making a 0.5.0 release.

**Comment by tolvanea** [comment]
Oh, my bad, thank you!
