### ISSUE TITLE
Plotting to term is broken since 0.5.0

### ISSUE THREAD

**Issue by xgillard** [milliams/plotlib#59]
Hi Matt, 

First thing first thank you a lot for writing this lib: I love it (especially since it means I dont have to resrort to python to plot my graphs). 

You've basically changed most of the APIs between 0.4.0 and 0.5.0, and thats perfectly fine (doc says api are in a state of flux) and I really like the new APIs however it turns out that I can no longer plot my graphs to terminal since I made the change (Saving to SVG is ok though).

**Comment by milliams** [comment]
Hi @xgillard,

I've fixed this (I think) and it should be sorted in 0.5.1 which will be released as soon as possible. I'll leave this issue open until then and if you could test it at that point and let me know if it's working for you.

**Comment by milliams** [comment]
0.5.1 is now released. Could you have a look and see if it fixed the problem for you?

**Comment by xgillard** [comment]
Yes, its been fixed. Now it works like a charm for me too. Thanks a lot !
