### ISSUE TITLE
API for specifying page dimensions

### ISSUE THREAD

**Issue by ManifoldFR** [milliams/plotlib#6]
Hi, I'm starting to use this crate to create plots as examples of my [point process simulation library](https://github.com/ManifoldFR/point-process-rust), and I thought it'd be nice if one could use custom dimensions for plots rather than the hard-coded ones.

Right now, I'm getting around it by getting the SVG document using the `as_view()` method from the `view::View` trait and manually saving the file.

If you'd like to, maybe I could make a pull request for this ?

**Comment by milliams** [comment]
Hi @ManifoldFR, glad to hear you're using the library. I'd welcome a PR indeed!

**Comment by ManifoldFR** [comment]
Well then, I'll get onto it !
