### ISSUE TITLE
Plans to replace failure dependency?

### ISSUE THREAD

**Issue by d-e-s-o** [milliams/plotlib#63]
The [`failure`](https://github.com/rust-lang-nursery/failure) crate that `plotlib` depends on [is deprecated](https://github.com/rust-lang-nursery/failure/commit/135e2a3b9af422d9a9dc37ce7c69354c9b36e94b). Are there plans to replace it?

**Comment by mindriot101** [comment]
I've been using [`thiserror`](https://crates.io/crates/thiserror) which is good for library errors.

**Comment by milliams** [comment]
I think that moving to `thiserror` makes sense. I'd happily accept a PR for this if I don't get round to it.

**Comment by milliams** [comment]
This was closed by #64
